mybatis:
  mapper-locations: classpath*:com/yingu/usermanagement/db/repository/mapper/*.xml
  type-aliases-package: com.yingu.usermanagement.db.repository
server:
  port: 8888

spring:
  datasource:
    hikari:
      driver-class-name: com.mysql.jdbc.Driver
      jdbc-url: jdbc:mysql://localhost:3306/test
      username: root
      password: 123456
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test
    username: root
    password: 123456
    type: com.zaxxer.hikari.HikariDataSource

  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    timeout: 6000
  #http://blog.didispace.com/springbootweb/
#  thymeleaf:
#    cache: true
#    check-template-location: true
#    content-type: text/html
#    enabled: true
#    encoding: utf-8
#    excluded-view-names:
#    mode: HTML5
    prefix: classpath:/templates
    suffix: .html
#    template-resolver-order:
#    view-names:



#spring.datasource.url=jdbc:mysql://localhost:3306/test
#spring.datasource.username=root
#spring.datasource.password=123456
#spring.datasource.driver-class-name=com.mysql.jdbc.Driver
#
##spring.jpa.properties.hibernate.hbm2ddl.auto=create-drop
#
#spring.mvc.view.prefix=/WEB-INF/jsps/
#spring.mvc.view.suffix=.jsp
#
#
##logging.config=classpath:log4j2.xml
#
##log Properties
#logging.file = demo.log
#logging.path = ./
#logging.level.* = info



#spring:
#  datasource.primary:
#    driverClassName: com.mysql.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/springboot?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull
#    username: root
#    password: root
#    initialSize: 5
#    minIdle: 5
#    maxActive: 20
#    filters: stat,wall,log4j
#  datasource.second:
#    driverClassName: com.mysql.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/public_declaration?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull
#    username: root
#    password: root
#    initialSize: 5
#    minIdle: 5
#    maxActive: 20
#filters: stat,wall,log4j


#logging:
#  file: springboot.log
#  level:
#    org:
#      mybatis: TRACE
#      springframework: INFO
#    online.zhaopei.myproject: TRACE
#    online.zhaopei.myproject.service: TRACE
#online.zhaopei.myproject.mapper: TRACE
